services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
      - ./var:/app/var
      - ./vendor:/app/vendor
    networks:
      - app-network
    ports:
      - "8000:8000"

networks:
  app-network: ~
